- name: testing
  hosts: frontend 
  tasks:
  - name: ping the server
    ansible.builtin.ping:
   
  
- name: test
  hosts: local 
  tasks:
  - name: hello the server
    ansible.builtin.debug:
      msg: "Hello i am shafi" 
   
  