- name: varible
  hosts: local
  connection: local
  vars:
    course: ansible
    duration: 10HR
    trainer: adam
  tasks:
   - name: course informatiom
     vars: 
     course: devops
     ansible.builtin.debug:
      msg: "hello {{ course }},course {{ duration }} course triner {{ trainer }}"



  # tasks:
  
  # - name: couser information
  #   course: aws and azure
  #   ansible.builtin.debug:
  #        msg: "hello {{ course }},course {{ duration }} course triner {{ trainer }}"