- name: varible
  hosts: local
  connection: local
  vars:
    course: ansible
    duration: 10HR
    trainer: adam

  tasks:
      - name: couser information
        ansible.builtin.debug:
         msg: "hello {{ course }},course {{ duration }} course triner {{ trainer }}"