- name: file from vars
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  - course2.yaml
  tasks:
  - name: all files data
    ansible.builtin.debug:
      msg: "my course{{ course }} is duration {{ duration }} and triner {{ trainer}}"