- name: numverdatatypes
  hosts: local
  connection: local
  vars:
   NUMBER: 99
  tasks: 
   - name: number is  leaasthen 100
     ansible.builtin.debug: 
      msg: "the number is {{ NUMBER }}"
  when: NUMBER < 100
