- name: conditions
  hosts: frontend
  become: yes
  tasks:
   - name: install nginx if state is redhat
     ansible.builtin.dnf:
       name: nginx
       state: present
     when: ansible_os_family == "RedHat"

   - name: start the services

     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes

   - name: install nginx if debian 
     ansible.builtin.apt:
       name: nginx
       state: present
     when: ansible_os_family == "Debian"
   - name: start the services

     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes