- name: loops
  hosts: frontend
  become: yes
  tasks:
    - name: loops installed
      ansible.builtin.package:
         name: "{{ item.name }}"
         state: "{{ item.state }}"
      loop:
      - { name: 'nginx', state: 'present' }
      - { name: 'mysql', state: 'absent' }
      - { name: 'zip', state: 'absent' }
