- name: functiondemo class
  hosts: local
  connection: local
  tasks: 
    - name: function demo default variable
      ansible.builtin.debug:
        msg: " Hello {{ 'ayeshahad' | default('shafi') }}"
