- name: shell vs command 
  hosts: frontend
  tasks:
   - name: chck command and shell
     ansible.builtin.command: "ls -lrt > /tmp/output.txt"
     #ansible.builtin.shell: "ls -lrt  > /tmp/output.txt"
     